version: 2.1
orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@0.0.10
jobs:
  circle-ci-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test

  heroku-deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          command: >
            cp .env.example .env
      - heroku/deploy-via-git

workflows:
  test:
    jobs:
      - circle-ci-test
  deploy:
    jobs:
      - heroku-deploy
